### ISSUE TITLE
Programme exits after analysing only some of the samples

### ISSUE THREAD

**Issue by Izzy-y** [LanLab/salty#5]
While running the software, I notice that the programme exits after analysing about 50  samples (this varies between 35-52 samples) out of for example 100.

My dependencies versions are python3.11; KMA-1.4.14; mlst 2.23.0 and pandas 1.5.3
I have pasted the error message below.

Any help you can provide to solve this error would be gratefully appreciated 

Traceback (most recent call last):
  File "/well/miniconda3/envs/salty/lib/python3.11/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
                    ^^^^^^^^^^^^^^^^^^^
  File "/well/miniconda3/envs/salty/lib/python3.11/multiprocessing/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/well/miniconda3/envs/salty/lib/python3.11/site-packages/salty/salty.py", line 21, in caller
    alleles = checkFailedLineage(alleles, path, args)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/well/miniconda3/envs/salty/lib/python3.11/site-packages/salty/salty.py", line 81, in checkFailedLineage
    associatedSaLTy = MLSTtoSaLTyDf[MLSTtoSaLTyDf['7-Gene-MLST'] == MLSTtype]['SaLTy-Lineage'].values[0]
                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: index 0 is out of bounds for axis 0 with size 0
"""
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/well/miniconda3/envs/salty/bin/salty", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/well/miniconda3/envs/salty/lib/python3.11/site-packages/salty/salty.py", line 271, in main
    run_multiprocessing(caller, inps, args.threads)
  File "/well/miniconda3/envs/salty/lib/python3.11/site-packages/salty/salty.py", line 247, in run_multiprocessing
    return pool.starmap(func, i)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/well/miniconda3/envs/salty/lib/python3.11/multiprocessing/pool.py", line 375, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/well/miniconda3/envs/salty/lib/python3.11/multiprocessing/pool.py", line 774, in get
    raise self._value
IndexError: index 0 is out of bounds for axis 0 with size 0

**Comment by mjohnpayne** [comment]
This should be resolved now. I will publish a new release and update conda shortly

**Comment by mjohnpayne** [comment]
version 1.0.6 fixes this issue and is now released available from bioconda. Thanks for pointing this out!

**Comment by Izzy-y** [comment]
Thank you very much for resolving the original issue so quickly. It is very kind of you.  Salty works on all of the samples in the input folder now. However, I have noticed two issues: 

1. A few genomes are in the "Mulitple Lineage Found" category and have two .csv files in their output folder. However, the second file does not have a genome column (see copied example text below), but only Lineage, SACOL1908, SACOL0451 and SACOL2725 columns.  Since the columns are unequal there are problems when summarising the .csv files from each folder.

ex. csv output file1 in folder 38293
Genome,Lineage,SACOL1908,SACOL0451,SACOL2725
38293,Mulitple Lineage Found,30,23,-

ex. csv output file2 in folder 38293
Lineage,SACOL1908,SACOL0451,SACOL2725
9,30.0,35.0,
54,,23.0,23.0

2. The second issue is regarding version no.  The version I have now installed shows it to be salty version: 1.0.7. You have mentioned that the latest update is 1.0.6. Could you please clarify?
Thank you!
